#ifndef SBX_ASSETS_VERSION_HPP_
#define SBX_ASSETS_VERSION_HPP_

#define SBX_ASSETS_VERSION_MAJOR 0
#define SBX_ASSETS_VERSION_MINOR 1
#define SBX_ASSETS_VERSION_PATCH 0

#define SBX_ASSETS_VERSION ((0 << 16) | (1 << 8) | 0)

#define SBX_ASSETS_VERSION_STRING "0.1.0"

#endif // SBX_ASSETS_VERSION_HPP_
