dependencies =
import dependencies += libsbx-core%liba{sbx_core}
import dependencies += gtest%liba{gtest}

exe{driver}: {hxx ixx txx cxx}{**} $dependencies testscript{**}
exe{driver}: test.arguments = '--gtest_color=yes'
