#ifndef LIBSBX_DEVICES_VERSION_HPP_
#define LIBSBX_DEVICES_VERSION_HPP_

#define LIBSBX_DEVICES_VERSION_MAJOR 0
#define LIBSBX_DEVICES_VERSION_MINOR 1
#define LIBSBX_DEVICES_VERSION_PATCH 0

#define LIBSBX_DEVICES_VERSION ((0 << 16) | (1 << 8) | 0)

#define LIBSBX_DEVICES_VERSION_STRING "0.1.0"

#endif // LIBSBX_DEVICES_VERSION_HPP_
