dependencies =
import dependencies += libsbx-math%liba{sbx_math}
import dependencies += gtest%liba{gtest}

exe{driver}: {hxx ixx txx cxx}{**} $dependencies testscript{**}
exe{driver}: test.arguments = '--gtest_color=yes' '--gtest_print_time=1'
