#ifndef SBX_GIZMOS_VERSION_HPP_
#define SBX_GIZMOS_VERSION_HPP_

#define SBX_GIZMOS_VERSION_MAJOR 0
#define SBX_GIZMOS_VERSION_MINOR 1
#define SBX_GIZMOS_VERSION_PATCH 0

#define SBX_GIZMOS_VERSION ((0 << 16) | (1 << 8) | 0)

#define SBX_GIZMOS_VERSION_STRING "0.1.0"

#endif // SBX_GIZMOS_VERSION_HPP_
