dependencies =
import dependencies += gtest%liba{gtest}
import dependencies += libsbx-devices%liba{sbx_devices}

exe{driver}: {hxx ixx txx cxx}{**} $dependencies testscript{**}
exe{driver}: test.arguments = '--gtest_color=yes' '--gtest_print_time=1'
