#ifndef SBX_BITMAPS_VERSION_HPP_
#define SBX_BITMAPS_VERSION_HPP_

#define SBX_BITMAPS_VERSION_MAJOR 0
#define SBX_BITMAPS_VERSION_MINOR 1
#define SBX_BITMAPS_VERSION_PATCH 0

#define SBX_BITMAPS_VERSION ((0 << 16) | (1 << 8) | 0)

#define SBX_BITMAPS_VERSION_STRING "0.1.0"

#endif // SBX_BITMAPS_VERSION_HPP_
