dependencies =
import dependencies += libsbx-utility%liba{sbx-utility}
import dependencies += libsbx-core%liba{sbx-core}
import dependencies += libsbx-devices%liba{sbx-devices}
import dependencies += libsbx-graphics%liba{sbx-graphics}

exe{demo}: {hxx ixx txx cxx}{**} $dependencies

cxx.poptions += "-I$out_root" "-I$src_root"
