dependencies =
import dependencies += libsbx-core%lib{sbx-core}
import dependencies += libsbx-ecs%lib{sbx-ecs}
import dependencies += libsbx-devices%lib{sbx-devices}

exe{demo}: {hxx ixx txx cxx}{**} $dependencies

cxx.poptions += "-I$out_root" "-I$src_root"
