public_dependencies =
import public_dependencies += spdlog%liba{spdlog}
import public_dependencies += libsbx-utility%liba{sbx-utility}

private_dependencies =

liba{sbx-core}: {hxx ixx txx cxx}{** -version} hxx{version} $private_dependencies $public_dependencies

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions += "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBSBX_CORE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBSBX_CORE_SHARED_BUILD

# Export options.
#
liba{sbx-core}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $public_dependencies
}

liba{sbx-core}: cxx.export.poptions += -DLIBSBX_CORE_STATIC
libs{sbx-core}: cxx.export.poptions += -DLIBSBX_CORE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{sbx-core}: bin.lib.version = "-$version.project_id"
else
  liba{sbx-core}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libsbx/core/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install = include/libsbx/core/
  install.subdirs = true
}
