#ifndef LIBSBX_PHYSICS_VERSION_HPP_
#define LIBSBX_PHYSICS_VERSION_HPP_

#define LIBSBX_PHYSICS_VERSION_MAJOR 0
#define LIBSBX_PHYSICS_VERSION_MINOR 1
#define LIBSBX_PHYSICS_VERSION_PATCH 0

#define LIBSBX_PHYSICS_VERSION ((0 << 16) | (1 << 8) | 0)

#define LIBSBX_PHYSICS_VERSION_STRING "0.1.0"

#endif // LIBSBX_PHYSICS_VERSION_HPP_
