public_dependencies = # Interface dependencies.
import public_dependencies += libsbx-core%lib{sbx-core}

private_dependencies = # Implementation dependencies.

lib{sbx-utility}: {hxx ixx txx cxx}{** -version} hxx{version} $private_dependencies $public_dependencies

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions += "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBSBX_UTILITY_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBSBX_UTILITY_SHARED_BUILD

# Export options.
#
lib{sbx-utility}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $public_dependencies
}

liba{sbx-utility}: cxx.export.poptions += -DLIBSBX_UTILITY_STATIC
libs{sbx-utility}: cxx.export.poptions += -DLIBSBX_UTILITY_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{sbx-utility}: bin.lib.version = "-$version.project_id"
else
  lib{sbx-utility}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libsbx/utility/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install = include/libsbx/utility/
  install.subdirs = true
}
