public_dependencies =
import public_dependencies += gtest%liba{gtest}
import public_dependencies += fmt%liba{fmt}

public_dependencies = $cxx.deduplicate_export_libs($public_dependencies)

private_dependencies =

lib{sbx_units}: {hxx ixx txx cxx}{** -version} hxx{version} $private_dependencies $public_dependencies

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions += "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBSBX_UNITS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBSBX_UNITS_SHARED_BUILD

# Export options.
#
lib{sbx_units}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $public_dependencies
}

liba{sbx_units}: cxx.export.poptions += -DLIBSBX_UNITS_STATIC
libs{sbx_units}: cxx.export.poptions += -DLIBSBX_UNITS_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{sbx_units}: bin.lib.version = "-$version.project_id"
else
  lib{sbx_units}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libsbx/units/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install = include/libsbx/units/
  install.subdirs = true
}
