dependencies = 
import dependencies += gtest%liba{gtest}
import dependencies += libsbx-signal%lib{sbx_signal}

exe{driver}: {hxx ixx txx cxx}{**} $dependencies testscript{**}
exe{driver}: test.arguments = '--gtest_color=yes' '--gtest_print_time=1'
